version: "3.7"

services:

  web:
    container_name: dashboard
    image: ghcr.io/tdex-network/dashboard:latest
    restart: unless-stopped
    environment:
      USE_PROXY: "true"
      # this must be the remote URL where this service is exposed
      # if ran locally it's fine localhost
      PROXY_URL: "http://localhost:3030"
    ports:
      - 8080:8080

  tdexd:
    container_name: "tdexd-proxy"
    image: ghcr.io/tdex-network/tdexd-proxy:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./tdexd-data:/home/tdex/.tdex-daemon
    environment:
      TDEX_NETWORK: regtest
      TDEX_BASE_ASSET: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      TDEX_LOG_LEVEL: 5
      TDEX_EXPLORER_ENDPOINT: http://chopsticks-liquid:3000 
    ports:
      - "3030:3030"
      - "9945:9945"
      - "9000:9000"

networks:
  default:
    external: true
    name: nigiri