name: "Release desktop apps"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Rust latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Install dasel
        run: |
          go install github.com/tomwright/dasel/cmd/dasel@latest

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: install app dependencies
        run: yarn install

      - name: build rpc proxy for amd & arm
        run: make crossbuild

      - name: tag
        id: next_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: version
        id: next_version
        run: |
          tag=${{ steps.next_tag.outputs.tag }}
          echo ::set-output name=version::${tag:1}

      - name: Git config and pull
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git config pull.rebase true
          git fetch origin master
          git pull origin master    

      - name: Increment version
        run: |
          dasel put string -f package.json ".version" "${{ steps.next_version.outputs.version }}"
          dasel put string -f src-tauri/tauri.conf.json ".package.version" "${{ steps.next_version.outputs.version }}"
          dasel put string -f src-tauri/Cargo.toml ".package.version" "${{ steps.next_version.outputs.version }}"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.next_tag.outputs.tag }}
          releaseName: "TDEX Dashboard ${{ steps.next_tag.outputs.tag }}"
          releaseBody: "See the assets to download this version and install."
          includeDebug: true

      # Commit package.json, tauri.conf.json and Cargo.toml to master
      - name: Commit & Push
        if: matrix.platform == 'ubuntu-latest'
        run: |
          git add .
          git commit -m "${{ steps.next_tag.outputs.tag }}"
          git push origin HEAD:master